### ISSUE TITLE
Can there be a toggle for creating aliases?

### ISSUE THREAD

**Issue by cyrus01337** [budimanjojo/tmux.fish#14]
Hi, new to Fish, not so new to Zsh, testing a migration at the moment

Loved this type of plugin when I use Zsh and love the work being put into this for Fish just as much. Has an option for disabling the creation of aliases ever been considered? I've personally never liked aliases that I don't set myself as I tend to forget them often, and wondered if this was something that should be implemented.

I'd be happy to help with as I understand this perspective appears niche from what I've seen.

**Comment by budimanjojo** [comment]
Hi, @cyrus01337! Thanks for the feature reques!

This plugin had some differences from the zsh version before I released v2.0.0 (which was a few days ago). But my main reason for v2 was to make this plugin work exactly the same as the zsh version

This should be an easy addition but I'm a little unsure on if I should have this switch because this will make this plugin different from the zsh version, but this is also a good addition and shouldn't cause any problem. For now I'll keep this issue open and I'll decide if I should add this.

For workaround, you can add something like this in your `config.fish` to remove the aliases: `functions -e <alias-you-want-to-delete>`. This will remove aliases created by this plugin.

**Comment by cyrus01337** [comment]
Ah, didn't think of removing aliases as I've never tried looking into that. Thank you so much!

I was wondering about the parity between the two plugins and didn't want to impose too much, I appreciate the workaround though. :)

**Comment by budimanjojo** [comment]
I went ahead and add this functionality. You can now do `set fish_tmux_no_alias true` in your `config.fish` and have those aliases except for `tmux` to be erased. Thanks for the FR!

**Comment by cyrus01337** [comment]
Thank youuu! :revolving_hearts:
