### ISSUE TITLE
Tmux not found on startup

### ISSUE THREAD

**Issue by icyrainz** [budimanjojo/tmux.fish#4]
I got this error when opening fish shell even though I have tmux installed (via homebrew)
```
fish tmux plugin: tmux not found. Please install tmux before using this plugin.
```

Although I have to manually add /opt/homebrew to path (since I'm on Apple silicon):

set PATH /opt/homebrew/bin $PATH
set PATH /opt/homebrew/sbin $PATH

My dotfiles:
https://github.com/icyrainz/.dotfiles/blob/master/fish/config.fish

**Comment by budimanjojo** [comment]
hello, currently I'm just using these lines to check for tmux executable: https://github.com/budimanjojo/tmux.fish/blob/87ef5c238b7fb133d7b49988c7c3fcb097953bd2/conf.d/tmux.fish#L1-L4
Not sure if there's any difference if there's a condition that `type` command doesn't work. Maybe u know anything about why it's not working so I can add to the code?

**Comment by budimanjojo** [comment]
Maybe `fish_add_path` in your dotfiles is being ran after `tmux.fish`?

**Comment by keponk** [comment]
same issue on a m1 mac ventura.
On my `config.fish`:
```
# homebrew
eval $(/opt/homebrew/bin/brew shellenv)
[...] // personasl abbrs etc
set -Ux fish_tmux_config $HOME/.config/tmux.conf
[...] // some configs not related to tmux nor fish
```

So the very first thing it does it setting up homebrew. so whenever i launch a terminal i can already run `type tmux` and get the correct answer.

I am not using `fish_add_path` anywhere on my dotfiles. Do you have other suggestions? 

I've edited that code to evaluate homebrew and that works but I imagine there must be a cleaner solution.
```
if not type -q tmux
    echo "fish tmux plugin: tmux not found. Please install tmux before using this plugin." >&2
    eval $(/opt/homebrew/bin/brew shellenv)
end
```

**Comment by budimanjojo** [comment]
@keponk thanks for the report. So the conclusion is this plugin ran before the `eval $(/opt/homebrew/bin/brew shellenv)` command that is needed for `homebrew` users? Do u have that line in your `config.fish` file? Maybe I can add the `eval` command if `homebrew` is installed like this:
```
if $homebrew
    eval $(/opt/homebrew/bin/brew shellenv)
end
```
Is this a reasonable fix?

**Comment by keponk** [comment]
@budimanjojo something similar should work  (technically you probably want to check for homebrew's default install dir, `$homebrew` doesn't evaluate to anything). I was still curious though and was looking around the fisher docs here:
https://github.com/jorgebucaran/fisher#creating-a-plugin 

But nothing popped up,  my curiosity is because I don't understand why this `eval` needs to exist, since I (and anyone else using homebrew) using other fisher plugins don't need to do this `eval` either.

One example is the nvm plugin by the same creator of `fisher` itself. https://github.com/jorgebucaran/nvm.fish/blob/main/conf.d/nvm.fish

they seem to be doing a lot less in the conf.d file, clearly they don't need to run this as soon as the terminal is started so I can understand some difference. But still, I would need to know more about the step by step process or how plugins are getting loaded by fish and fisher.

in the meantime, I could provide a quick PR for the workaround. PR coming in a bit.

**Comment by budimanjojo** [comment]
@keponk The example `nvm` plugin doesn't need `eval` is because it's using the `nvm` function from the `./functions` directory here: https://github.com/jorgebucaran/nvm.fish/blob/c69e5d1017b21bcfca8f42c93c7e89fff6141a8a/functions/nvm.fish#L1
It's not using the `nvm` installed in the OS at all it seems

**Comment by icyrainz** [comment]
Update: switching to use fish_add_path API to add homebrew paths did resolve the problem but I'm not sure why.

**Comment by budimanjojo** [comment]
Closed by: https://github.com/budimanjojo/tmux.fish/pull/5
